name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Frontend to VPS
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Deploy to VPS and Build
        run: |
          sshpass -p "PAbCptqKYwJ2D43Lx@9X" ssh -o StrictHostKeyChecking=no root@161.248.1.254 << 'EOF'
            # Load nvm
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Use Node.js 20
            nvm use 20
            cd /var/www/netsbay-frontend

            echo "Node Version: $(node -v)"
            echo "NPM Version: $(npm -v)"
            node -v
            npm -v
            # Pull latest changes
            git reset --hard
            git pull origin main

            # Install dependencies
            npm install

            # Run build
            npm run build

          EOF

          